name: DiemDanh
version: '1.4-BETA'
main: me.diemdanh.DiemDanh
api-version: '1.13'
commands:
  diemdanh:
    description: Mở GUI điểm danh hàng ngày
    usage: /diemdanh [reload] [giveticket <player> <amount>]
    permission: diemdanh.use
permissions:
  diemdanh.use:
    description: Cho phép người chơi sử dụng lệnh /diemdanh
    default: true
  diemdanh.top:
    description: Cho phép người chơi sử dụng lệnh /diemdanh top
    default: true
  diemdanh.reload:
    description: Cho phép người chơi sử dụng lệnh /diemdanh reload
    default: op
  diemdanh.giveticket:
    description: Cho phép người chơi sử dụng lệnh /diemdanh giveticket
    default: op
softdepend: [HeadDatabase]
